// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

public partial class City
{
    [Key]
    public long Id { get; set; }

    public long ProvinceId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EnglishName { get; set; }

    [StringLength(50)]
    public string TosanCodeNew { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string OldCode { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Shop> Shops { get; } = new List<Shop>();
}