// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

public partial class CommissionType
{
    [Key]
    public long Id { get; set; }

    [Required]
    [StringLength(50)]
    public string SahredType { get; set; }

    public byte SharedTypeCode { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [InverseProperty("ShareType")]
    public virtual ICollection<Contract> Contracts { get; } = new List<Contract>();

    [InverseProperty("ShareType")]
    public virtual ICollection<Iban> Ibans { get; } = new List<Iban>();

    [InverseProperty("ShareType")]
    public virtual ICollection<MarketerContract> MarketerContracts { get; } = new List<MarketerContract>();

    [InverseProperty("ShareType")]
    public virtual ICollection<Project> Projects { get; } = new List<Project>();

    [InverseProperty("ShareType")]
    public virtual ICollection<RequestIban> RequestIbans { get; } = new List<RequestIban>();
}