// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Index("CustomerId", Name = "IX_Contracts_CustomerId")]
[Index("ProjectId", Name = "IX_Contracts_ProjectId")]
[Index("ShareTypeId", Name = "IX_Contracts_ShareTypeId")]
public partial class Contract
{
    [Key]
    public long Id { get; set; }

    [Required]
    [StringLength(50)]
    public string ContractNumber { get; set; }

    public byte[] ContractDate { get; set; }

    public long? CustomerId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExpireDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ServiceStartDate { get; set; }

    public string Description { get; set; }

    public long? ProjectId { get; set; }

    public long? ShareTypeId { get; set; }

    public double? ShareAmount { get; set; }

    public long? ShareAmountMax { get; set; }

    public long? ShareAmountMin { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Contracts")]
    public virtual Shop Customer { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("Contracts")]
    public virtual Project Project { get; set; }

    [ForeignKey("ShareTypeId")]
    [InverseProperty("Contracts")]
    public virtual CommissionType ShareType { get; set; }
}