// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

public partial class Country
{
    [Key]
    public long Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Code { get; set; }

    [StringLength(50)]
    public string Abbrivation { get; set; }

    [StringLength(50)]
    public string PersianName { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [InverseProperty("Country")]
    public virtual ICollection<Person> PersonCountries { get; } = new List<Person>();

    [InverseProperty("NationalityCountry")]
    public virtual ICollection<Person> PersonNationalityCountries { get; } = new List<Person>();
}