// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Index("CustomerId", Name = "IX_CustomersIbans_CustomerId")]
[Index("ShareTypeId", Name = "IX_CustomersIbans_ShareTypeId")]
public partial class Iban
{
    [Key]
    public long Id { get; set; }

    [Column("Iban")]
    [StringLength(30)]
    public string Iban1 { get; set; }

    public long? PersonId { get; set; }

    public long? CustomerId { get; set; }

    [StringLength(30)]
    public string AccountNumber { get; set; }

    public long? ShareTypeId { get; set; }

    public double? SharedAmount { get; set; }

    public long? ShareAmountMax { get; set; }

    public long? ShareAmountMin { get; set; }

    public bool? IsMain { get; set; }

    public byte? OrderNo { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Ibans")]
    public virtual Shop Customer { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("Ibans")]
    public virtual Person Person { get; set; }

    [ForeignKey("ShareTypeId")]
    [InverseProperty("Ibans")]
    public virtual CommissionType ShareType { get; set; }
}