// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Table("MarketerContract")]
[Index("CustomerId", Name = "IX_MarketerContract_CustomerId")]
[Index("MarketerPersonId", Name = "IX_MarketerContract_MarketerPersonId")]
[Index("ShareTypeId", Name = "IX_MarketerContract_ShareTypeId")]
public partial class MarketerContract
{
    [Key]
    public long Id { get; set; }

    public byte[] ContractDate { get; set; }

    public string Description { get; set; }

    public long ShareTypeId { get; set; }

    public double? SharedAmount { get; set; }

    public long? ShareAmountMax { get; set; }

    public long? ShareAmountMin { get; set; }

    [Required]
    [StringLength(30)]
    public string Iban { get; set; }

    public long CustomerId { get; set; }

    public long MarketerPersonId { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("MarketerContracts")]
    public virtual Shop Customer { get; set; }

    [ForeignKey("MarketerPersonId")]
    [InverseProperty("MarketerContracts")]
    public virtual Person MarketerPerson { get; set; }

    [ForeignKey("ShareTypeId")]
    [InverseProperty("MarketerContracts")]
    public virtual CommissionType ShareType { get; set; }
}