// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Table("MerchantSyncTable")]
public partial class MerchantSyncTable
{
    [Key]
    public long id { get; set; }

    public long? merchantid { get; set; }

    public byte? SyncType { get; set; }

    public bool? issynced { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createdate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? syncdate { get; set; }
}