// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Configuration;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Index("BirthCertificateAlphabiticNoId", Name = "IX_Persons_BirthCertificateAlphabiticNoId")]
[Index("CountryId", Name = "IX_Persons_CountryId")]
[Index("DegreeId", Name = "IX_Persons_DegreeId")]
[Index("NationalityCountryId", Name = "IX_Persons_NationalityCountryId")]
public partial class Person
{
    [Key]
    public long Id { get; set; }

    public bool? IsDisable { get; set; }

    [Required]
    [StringLength(10)]
    public string NationalNumber { get; set; }

    [Required]
    public string FirstNameFa { get; set; }

    [Required]
    public string LastNameFa { get; set; }

    public string FirstNameEn { get; set; }

    public string LastNameEn { get; set; }

    public long? NationalityCountryId { get; set; }

    public string BirthLocation { get; set; }

    [StringLength(10)]
    public string BirthDate { get; set; }

    public string BirthCertificatePlaceOfIssue { get; set; }

    public string FatherNameFa { get; set; }

    public string FatherNameEn { get; set; }

    public bool? Gender { get; set; }

    public long? BirthCertificateNo { get; set; }

    public int? BirthCertificateSerial { get; set; }

    public long? BirthCertificateAlphabiticNoId { get; set; }

    public int? BirthCertificateNumericNo { get; set; }

    public long? DegreeId { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    public bool? IsLegal { get; set; }

    public bool? IsForeign { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string RegisterDate { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string RegisterNo { get; set; }

    [Unicode(false)]
    public string ComNameEn { get; set; }

    public string ComNameFa { get; set; }

    public bool? RsidencyType { get; set; }

    public bool? VitalStatus { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string NationalLegalCode { get; set; }

    public long? CountryId { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string CountryAbbrivation { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ForeignPervasiveCode { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PassportNo { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string PassportExpireDate { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string CommercialCode { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }


    public long PersonTypeId { get; set; }

    [ForeignKey("BirthCertificateAlphabiticNoId")]
    [InverseProperty("People")]
    public virtual Alphabet BirthCertificateAlphabiticNo { get; set; }

    [ForeignKey("CountryId")]
    [InverseProperty("PersonCountries")]
    public virtual Country Country { get; set; }

    [ForeignKey("DegreeId")]
    [InverseProperty("People")]
    public virtual Degree Degree { get; set; }

    [InverseProperty("Person")]
    public virtual ICollection<Iban> Ibans { get; } = new List<Iban>();

    [InverseProperty("MarketerPerson")]
    public virtual ICollection<MarketerContract> MarketerContracts { get; } = new List<MarketerContract>();

    [ForeignKey("NationalityCountryId")]
    [InverseProperty("PersonNationalityCountries")]
    public virtual Country NationalityCountry { get; set; }

    [InverseProperty("Person")]
    public virtual ICollection<ShopPerson> ShopPeople { get; } = new List<ShopPerson>();
}