// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Index("ShareTypeId", Name = "IX_Projects_ShareTypeId")]
public partial class Project
{
    [Key]
    public long Id { get; set; }

    [Required]
    [StringLength(300)]
    public string Name { get; set; }

    public long ShareTypeId { get; set; }

    public double? SharedAmount { get; set; }

    public long? ShareAmountMax { get; set; }

    public long? ShareAmountMin { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<Contract> Contracts { get; } = new List<Contract>();

    [ForeignKey("ShareTypeId")]
    [InverseProperty("Projects")]
    public virtual CommissionType ShareType { get; set; }
}