// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Table("PSP")]
public partial class PSP
{
    [Key]
    public long Id { get; set; }

    [StringLength(50)]
    public string UserShaparak { get; set; }

    [StringLength(50)]
    public string PasswordShaparak { get; set; }

    [StringLength(50)]
    public string PspMmsUsername { get; set; }

    [StringLength(50)]
    public string PspMmsPassword { get; set; }

    public string PspMmsPublicKey { get; set; }

    public string PspMmsPrivateKey { get; set; }

    public string ShaparakFtpPublicKey { get; set; }

    public string ShaparakFtpPrivateKey { get; set; }

    [StringLength(150)]
    public string Name { get; set; }

    [StringLength(150)]
    public string Alias { get; set; }

    [StringLength(50)]
    public string ShaparakFtpUsername { get; set; }

    [StringLength(50)]
    public string ShaparakFtpPassword { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string IIN { get; set; }

    [StringLength(8)]
    [Unicode(false)]
    public string TerminalNo { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string AcceptorCode { get; set; }

    public byte? StepsCount { get; set; }

    public bool? Enabled { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    public TimeOnly? CutOffTime { get; set; }

    public string SettlementIban { get; set; }

    public string WageIban { get; set; }

    public string TlsHostCertificateFingerprint { get; set; }

    [InverseProperty("Psp")]
    public virtual ICollection<Merchant> Merchants { get; } = new List<Merchant>();

    [InverseProperty("Psp")]
    public virtual ICollection<Request> Requests { get; } = new List<Request>();
}