// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Index("RequestId", Name = "IX_RequestDetails_RequestId")]
public partial class RequestDetail
{
    [Key]
    public long Id { get; set; }

    public long RequestId { get; set; }

    public string PrevValue { get; set; }

    [Required]
    public string NewValue { get; set; }

    public string Description { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [ForeignKey("RequestId")]
    [InverseProperty("RequestDetails")]
    public virtual Request Request { get; set; }
}