// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

public partial class RequestType
{
    [Key]
    public long Id { get; set; }

    [StringLength(150)]
    public string Request { get; set; }

    [StringLength(150)]
    public string PspRequestTitle { get; set; }

    public byte? PspRequestCode { get; set; }

    [StringLength(150)]
    public string ShaparakSatetTitle { get; set; }

    public byte? ShaparakSatetCode { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [InverseProperty("RequestType")]
    public virtual ICollection<Request> Requests { get; } = new List<Request>();
}