// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Index("CustomerId", Name = "IX_Requests_CustomerId")]
[Index("MerchantId", Name = "IX_Requests_MerchantId")]
[Index("PspId", Name = "IX_Requests_PspId")]
[Index("RequestStateId", Name = "IX_Requests_RequestStateId")]
[Index("RequestTypeId", Name = "IX_Requests_RequestTypeId")]
public partial class Request
{
    [Key]
    public long Id { get; set; }

    public long? CustomerId { get; set; }

    [StringLength(10)]
    public string InstallationDate { get; set; }

    public string Description { get; set; }

    public string ShaparakDescription { get; set; }

    public long? RequestTypeId { get; set; }

    public long? PspId { get; set; }

    public long? RequestStateId { get; set; }

    public string ShaparakTrackingNumber { get; set; }

    public Guid? TrackingNumber { get; set; }

    public byte? ShaparakState { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastCallTime { get; set; }

    public DateTime? InsertDateTime { get; set; }

    [Unicode(false)]
    public string RequestData { get; set; }

    public string EditedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    public long? MerchantId { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Requests")]
    public virtual Shop Customer { get; set; }

    [ForeignKey("MerchantId")]
    [InverseProperty("Requests")]
    public virtual Merchant Merchant { get; set; }

    [ForeignKey("PspId")]
    [InverseProperty("Requests")]
    public virtual PSP Psp { get; set; }

    [InverseProperty("Request")]
    public virtual ICollection<RequestDetail> RequestDetails { get; } = new List<RequestDetail>();

    [InverseProperty("Request")]
    public virtual ICollection<RequestIban> RequestIbans { get; } = new List<RequestIban>();

    [ForeignKey("RequestStateId")]
    [InverseProperty("Requests")]
    public virtual RequestState RequestState { get; set; }

    [ForeignKey("RequestTypeId")]
    [InverseProperty("Requests")]
    public virtual RequestType RequestType { get; set; }
}