// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

public partial class ShopPerson
{
    [Key]
    public long Id { get; set; }

    public long ShopId { get; set; }

    public long PersonId { get; set; }

    public bool IsMainPerson { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("ShopPeople")]
    public virtual Person Person { get; set; }

    [ForeignKey("ShopId")]
    [InverseProperty("ShopPeople")]
    public virtual Shop Shop { get; set; }
}