// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMSApp.Models;

[Index("CityId", Name = "IX_Customers_CityId")]
[Index("GuildCategoryId", Name = "IX_Customers_GuildCategoryId")]
public partial class Shop
{
    [Key]
    public long Id { get; set; }

    [Unicode(false)]
    public string Telephone { get; set; }

    public string AddressFa { get; set; }

    [Unicode(false)]
    public string AddressEn { get; set; }

    public string WebSiteAddress { get; set; }

    public bool? IsSharedAccount { get; set; }

    public bool? IsMultiAccount { get; set; }

    public string ShopPostalCode { get; set; }

    [Unicode(false)]
    public string ShopFaxNumber { get; set; }

    public string ShopCityPreCode { get; set; }

    public string ShopBusinessLicenseNumber { get; set; }

    public string ShopBusinessLicenseIssueDate { get; set; }

    public string ShopBusinessLicenseExpireDate { get; set; }

    public string ShopEmail { get; set; }

    [Unicode(false)]
    public string BusinesslicenseImage { get; set; }

    [Unicode(false)]
    public string RedirectUrl { get; set; }

    public long GuildCategoryId { get; set; }

    [Unicode(false)]
    public string ShopLogo { get; set; }

    public string CustomerKey { get; set; }

    public string CustomerValue { get; set; }

    public string ShopNameFa { get; set; }

    [Unicode(false)]
    public string ShopNameEn { get; set; }

    public long? CityId { get; set; }

    [StringLength(50)]
    public string CityCode { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string taxPayerCode { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public long CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public long? UpdaterUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("Shops")]
    public virtual City City { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Contract> Contracts { get; } = new List<Contract>();

    [ForeignKey("GuildCategoryId")]
    [InverseProperty("Shops")]
    public virtual GuildCategory GuildCategory { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Iban> Ibans { get; } = new List<Iban>();

    [InverseProperty("Customer")]
    public virtual ICollection<MarketerContract> MarketerContracts { get; } = new List<MarketerContract>();

    [InverseProperty("Customer")]
    public virtual ICollection<Merchant> Merchants { get; } = new List<Merchant>();

    [InverseProperty("Customer")]
    public virtual ICollection<Request> Requests { get; } = new List<Request>();

    [InverseProperty("Shop")]
    public virtual ICollection<ShopPerson> ShopPeople { get; } = new List<ShopPerson>();
}